name: expense_repository
description: The Repo that handles expenses
publish_to: "none"
version: 1.0.1+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.0
  firebase_auth: ^5.0.0
  flutter:
    sdk: flutter
  # flutter_bloc: ^8.1.5
  # uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
