// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
/// options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtC7UV9673MvoCvbk1bXtB3yD7HxR1Rnc',
    appId: '1:880389850928:web:3c6b9713f3ad0b1f556af5',
    messagingSenderId: '880389850928',
    projectId: 'expenso-e4e26',
    authDomain: 'expenso-e4e26.firebaseapp.com',
    storageBucket: 'expenso-e4e26.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbR6BaYBLq-097IyWCSJKQWIitnlXVUmw',
    appId: '1:880389850928:android:d0c9710acdf41605556af5',
    messagingSenderId: '880389850928',
    projectId: 'expenso-e4e26',
    storageBucket: 'expenso-e4e26.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQuOJH4ThOo2QGgBMteFX8SHJL1KaSeFI',
    appId: '1:880389850928:ios:44e8d801f1cd7ed2556af5',
    messagingSenderId: '880389850928',
    projectId: 'expenso-e4e26',
    storageBucket: 'expenso-e4e26.appspot.com',
    iosBundleId: 'com.dcaayush.codes.expensoExpenseTracker',
  );
}
